import { baseListing, mockId, mockImages } from "./helpers";
import type { Listing } from "@/types/listing";
import type { HizmetVerenlerDetails } from "@/types/listing-fields";

function hizmetDetails(
  partial: Partial<HizmetVerenlerDetails> &
    Pick<HizmetVerenlerDetails, "serviceType" | "priceType" | "serviceCities">,
): HizmetVerenlerDetails {
  return {
    isCompany: false,
    emergencyService: false,
    sameDayService: false,
    weekendAvailable: false,
    bringsEquipment: false,
    materialIncluded: false,
    warrantyOffered: false,
    invoiceAvailable: false,
    ...partial,
  };
}

/** 12 örnek hizmet veren ilanı */
export const MOCK_HIZMET_VERENLER_LISTINGS: Listing[] = [
  baseListing({
    id: mockId(),
    userId: "usr-hizmet-ankara",
    category: "hizmet-verenler",
    title: "Ankara tayin sonrası profesyonel ev temizliği",
    description:
      "Taşınma öncesi/sonrası detaylı temizlik, mutfak ve banyo hijyeni. Memur ailelere öncelikli randevu.",
    contactName: "Gül Temizlik",
    whatsapp: "05321110001",
    cityFrom: "Ankara",
    districtFrom: "Çankaya",
    price: 2500,
    images: mockImages("hizmet-ankara-temizlik", 2),
    status: "approved",
    isUrgent: false,
    isFeatured: true,
    reportCount: 0,
    details: hizmetDetails({
      serviceType: "temizlik",
      serviceTitle: "Taşınma sonrası komple ev temizliği",
      serviceCities: ["Ankara"],
      serviceDistricts: ["Çankaya", "Keçiören", "Yenimahalle"],
      workingDays: "Pzt–Cmt",
      workingHours: "08:00–19:00",
      experienceYears: 8,
      isCompany: true,
      companyName: "Gül Temizlik Hizmetleri",
      teamSize: 4,
      priceType: "is-basina",
      startingPrice: 2500,
      emergencyService: false,
      sameDayService: true,
      weekendAvailable: true,
      bringsEquipment: true,
      materialIncluded: true,
      warrantyOffered: false,
      invoiceAvailable: true,
      descriptionOfService: "3+1 daire ortalama 6–8 saat, malzeme dahil.",
      averageResponseTime: "1 saat",
    }),
  }),
  baseListing({
    id: mockId(),
    userId: "usr-hizmet-bursa",
    category: "hizmet-verenler",
    title: "Bursa boya badana — hızlı ve temiz işçilik",
    description: "İç cephe boya, badana ve küçük alçı onarım. Tayin taşınmalarına uygun paket fiyat.",
    contactName: "Usta Mehmet",
    whatsapp: "05322220002",
    cityFrom: "Bursa",
    districtFrom: "Nilüfer",
    price: 180,
    images: mockImages("hizmet-bursa-boya", 3),
    status: "approved",
    isUrgent: false,
    isFeatured: false,
    reportCount: 0,
    details: hizmetDetails({
      serviceType: "boya-badana",
      serviceCities: ["Bursa"],
      serviceDistricts: ["Nilüfer", "Osmangazi"],
      workingDays: "Pzt–Cum",
      workingHours: "09:00–18:00",
      experienceYears: 15,
      isCompany: false,
      teamSize: 2,
      priceType: "gunluk",
      startingPrice: 3500,
      sameDayService: false,
      weekendAvailable: false,
      bringsEquipment: true,
      materialIncluded: false,
      warrantyOffered: true,
      invoiceAvailable: false,
      averageResponseTime: "3 saat",
    }),
  }),
  baseListing({
    id: mockId(),
    userId: "usr-hizmet-siirt",
    category: "hizmet-verenler",
    title: "Siirt tesisat ve su tesisatı onarım",
    description: "Musluk, sifon, klozet, petek ve küçük kaçak onarımları.",
    contactName: "Ahmet Usta",
    whatsapp: "05343330003",
    cityFrom: "Siirt",
    districtFrom: "Merkez",
    images: mockImages("hizmet-siirt-tesisat", 1),
    status: "approved",
    isUrgent: true,
    isFeatured: false,
    reportCount: 0,
    details: hizmetDetails({
      serviceType: "tesisat",
      serviceCities: ["Siirt"],
      experienceYears: 12,
      isCompany: false,
      priceType: "teklif-al",
      emergencyService: true,
      sameDayService: true,
      weekendAvailable: true,
      bringsEquipment: true,
      materialIncluded: false,
      warrantyOffered: true,
      invoiceAvailable: false,
      averageResponseTime: "30 dk",
    }),
  }),
  baseListing({
    id: mockId(),
    userId: "usr-hizmet-van",
    category: "hizmet-verenler",
    title: "Van elektrik tesisat ve arıza servisi",
    description: "Priz, sigorta, aydınlatma ve küçük tadilat elektrik işleri.",
    contactName: "Van Elektrik",
    whatsapp: "05324440004",
    cityFrom: "Van",
    districtFrom: "İpekyolu",
    price: 500,
    images: mockImages("hizmet-van-elektrik", 2),
    status: "approved",
    isUrgent: false,
    isFeatured: false,
    reportCount: 0,
    details: hizmetDetails({
      serviceType: "elektrik",
      serviceCities: ["Van"],
      serviceDistricts: ["İpekyolu", "Edremit"],
      experienceYears: 10,
      isCompany: true,
      companyName: "Van Elektrik Servis",
      teamSize: 3,
      priceType: "is-basina",
      startingPrice: 500,
      emergencyService: true,
      sameDayService: true,
      weekendAvailable: true,
      bringsEquipment: true,
      invoiceAvailable: true,
      averageResponseTime: "2 saat",
    }),
  }),
  baseListing({
    id: mockId(),
    userId: "usr-hizmet-diyarbakir",
    category: "hizmet-verenler",
    title: "Diyarbakır mobilya montaj ve kurulum",
    description: "IKEA ve yerli marka mobilya montajı, duvar askısı, mutfak dolabı kurulumu.",
    contactName: "Montaj Ekibi DK",
    whatsapp: "05325550005",
    cityFrom: "Diyarbakır",
    districtFrom: "Kayapınar",
    price: 800,
    images: mockImages("hizmet-diyarbakir-montaj", 2),
    status: "approved",
    isUrgent: false,
    isFeatured: false,
    reportCount: 0,
    details: hizmetDetails({
      serviceType: "mobilya-montaj",
      serviceCities: ["Diyarbakır"],
      experienceYears: 6,
      isCompany: true,
      companyName: "DK Montaj",
      teamSize: 2,
      priceType: "is-basina",
      startingPrice: 800,
      sameDayService: true,
      weekendAvailable: true,
      bringsEquipment: true,
      materialIncluded: false,
      warrantyOffered: false,
      invoiceAvailable: true,
      averageResponseTime: "4 saat",
    }),
  }),
  baseListing({
    id: mockId(),
    userId: "usr-hizmet-mardin",
    category: "hizmet-verenler",
    title: "Mardin perde ve korniş montaj",
    description: "Stor, zebra, tül perde ve korniş montajı. Ölçü alımı ücretsiz.",
    contactName: "Perde Evi Mardin",
    whatsapp: "05326660006",
    cityFrom: "Mardin",
    districtFrom: "Artuklu",
    price: 1200,
    images: mockImages("hizmet-mardin-perde", 2),
    status: "approved",
    isUrgent: false,
    isFeatured: false,
    reportCount: 0,
    details: hizmetDetails({
      serviceType: "perde-kornis",
      serviceCities: ["Mardin"],
      isCompany: true,
      companyName: "Perde Evi Mardin",
      teamSize: 2,
      priceType: "sabit-fiyat",
      startingPrice: 1200,
      weekendAvailable: true,
      bringsEquipment: true,
      materialIncluded: false,
      invoiceAvailable: true,
      averageResponseTime: "1 gün",
    }),
  }),
  baseListing({
    id: mockId(),
    userId: "usr-hizmet-izmir",
    category: "hizmet-verenler",
    title: "İzmir klima bakım ve montaj servisi",
    description: "Split klima montaj, gaz dolumu ve mevsimlik bakım.",
    contactName: "Ege Klima",
    whatsapp: "05327770007",
    cityFrom: "İzmir",
    districtFrom: "Karşıyaka",
    price: 1500,
    images: mockImages("hizmet-izmir-klima", 2),
    status: "approved",
    isUrgent: false,
    isFeatured: true,
    reportCount: 0,
    details: hizmetDetails({
      serviceType: "klima-servisi",
      serviceCities: ["İzmir"],
      serviceDistricts: ["Karşıyaka", "Bornova", "Konak"],
      experienceYears: 9,
      isCompany: true,
      companyName: "Ege Klima Servis",
      teamSize: 3,
      priceType: "is-basina",
      startingPrice: 1500,
      warrantyOffered: true,
      invoiceAvailable: true,
      sameDayService: false,
      weekendAvailable: true,
      averageResponseTime: "6 saat",
    }),
  }),
  baseListing({
    id: mockId(),
    userId: "usr-hizmet-erzurum",
    category: "hizmet-verenler",
    title: "Erzurum internet ve uydu kurulum",
    description: "Fiber modem kurulumu, Wi-Fi optimizasyonu ve çanak anten ayarı.",
    contactName: "Doğu Net",
    whatsapp: "05328880008",
    cityFrom: "Erzurum",
    districtFrom: "Yakutiye",
    price: 600,
    images: mockImages("hizmet-erzurum-net", 1),
    status: "approved",
    isUrgent: false,
    isFeatured: false,
    reportCount: 0,
    details: hizmetDetails({
      serviceType: "internet-uydu",
      serviceCities: ["Erzurum"],
      isCompany: true,
      companyName: "Doğu Net Kurulum",
      priceType: "sabit-fiyat",
      startingPrice: 600,
      sameDayService: true,
      weekendAvailable: true,
      bringsEquipment: true,
      invoiceAvailable: true,
      averageResponseTime: "2 saat",
    }),
  }),
  baseListing({
    id: mockId(),
    userId: "usr-hizmet-istanbul",
    category: "hizmet-verenler",
    title: "İstanbul küçük ev onarım ve tadilat",
    description: "Kapı ayarı, dolap tamiri, sıva ve boya touch-up. Tayin taşınmalarına özel.",
    contactName: "Tamirat Pro",
    whatsapp: "05329990009",
    cityFrom: "İstanbul",
    districtFrom: "Kadıköy",
    images: mockImages("hizmet-istanbul-onarim", 3),
    status: "approved",
    isUrgent: false,
    isFeatured: true,
    reportCount: 0,
    details: hizmetDetails({
      serviceType: "ev-onarim",
      serviceCities: ["İstanbul"],
      serviceDistricts: ["Kadıköy", "Üsküdar", "Ataşehir"],
      experienceYears: 14,
      isCompany: true,
      companyName: "Tamirat Pro İstanbul",
      teamSize: 5,
      priceType: "teklif-al",
      emergencyService: false,
      sameDayService: false,
      weekendAvailable: true,
      bringsEquipment: true,
      warrantyOffered: true,
      invoiceAvailable: true,
      averageResponseTime: "1 gün",
    }),
  }),
  baseListing({
    id: mockId(),
    userId: "usr-hizmet-konya",
    category: "hizmet-verenler",
    title: "Konya günlük ve taşınma temizliği",
    description: "Boş ev teslim temizliği, buzdolabı ve fırın detaylı temizlik.",
    contactName: "Selin H.",
    whatsapp: "05321010010",
    cityFrom: "Konya",
    districtFrom: "Selçuklu",
    price: 120,
    images: mockImages("hizmet-konya-temizlik", 2),
    status: "approved",
    isUrgent: false,
    isFeatured: false,
    reportCount: 0,
    details: hizmetDetails({
      serviceType: "temizlik",
      serviceCities: ["Konya"],
      experienceYears: 5,
      isCompany: false,
      priceType: "saatlik",
      startingPrice: 350,
      sameDayService: true,
      weekendAvailable: true,
      bringsEquipment: true,
      materialIncluded: true,
      invoiceAvailable: false,
      averageResponseTime: "2 saat",
    }),
  }),
  baseListing({
    id: mockId(),
    userId: "usr-hizmet-antalya",
    category: "hizmet-verenler",
    title: "Antalya 7/24 çilingir ve anahtar hizmeti",
    description: "Kapı açma, kilit değişimi ve çelik kapı ayarı.",
    contactName: "Akdeniz Çilingir",
    whatsapp: "05322110011",
    cityFrom: "Antalya",
    districtFrom: "Muratpaşa",
    price: 800,
    images: mockImages("hizmet-antalya-cilingir", 1),
    status: "approved",
    isUrgent: true,
    isFeatured: false,
    reportCount: 0,
    details: hizmetDetails({
      serviceType: "anahtar-cilingir",
      serviceCities: ["Antalya"],
      isCompany: true,
      companyName: "Akdeniz Çilingir",
      priceType: "is-basina",
      startingPrice: 800,
      emergencyService: true,
      sameDayService: true,
      weekendAvailable: true,
      averageResponseTime: "20 dk",
    }),
  }),
  baseListing({
    id: mockId(),
    userId: "usr-hizmet-kayseri",
    category: "hizmet-verenler",
    title: "Kayseri nakliye yardımcı personel",
    description: "Taşınma günü yükleme-boşaltma, paket taşıma. Saatlik veya günlük.",
    contactName: "Yük Ekibi Kayseri",
    whatsapp: "05323220012",
    cityFrom: "Kayseri",
    districtFrom: "Melikgazi",
    price: 400,
    images: mockImages("hizmet-kayseri-nakliye", 1),
    status: "approved",
    isUrgent: false,
    isFeatured: false,
    reportCount: 0,
    details: hizmetDetails({
      serviceType: "nakliye-yardimci-personel",
      serviceCities: ["Kayseri"],
      isCompany: true,
      companyName: "Yük Ekibi",
      teamSize: 6,
      priceType: "saatlik",
      startingPrice: 400,
      sameDayService: true,
      weekendAvailable: true,
      bringsEquipment: false,
      invoiceAvailable: false,
      averageResponseTime: "1 saat",
    }),
  }),
];
