import { MOCK_HIZMET_VERENLER_LISTINGS } from "./hizmet-verenler-listings";
import { baseListing, mockId, mockImages } from "./helpers";
import type { Listing } from "@/types/listing";

export const MOCK_LISTINGS: Listing[] = [
  // —— Ev Devri (5) ——
  baseListing({
    id: mockId(),
    category: "ev-devri",
    title: "Ankara Çankaya 2+1 ev devri — depozito dahil",
    description:
      "Sağlık Bakanlığı tayini nedeniyle devrediyorum. Site içi, güvenlikli, otopark mevcut.",
    contactName: "Ayşe K.",
    whatsapp: "05321234567",
    cityFrom: "Ankara",
    districtFrom: "Çankaya",
    price: 18500,
    images: mockImages("ev-ankara", 3),
    status: "approved",
    isUrgent: true,
    isFeatured: true,
    reportCount: 0,
    details: {
      neighborhood: "Kızılay",
      roomCount: "2+1",
      floor: 4,
      buildingAge: 8,
      rentPrice: 18500,
      deposit: 18500,
      dues: 450,
      furnished: "evet",
      heatingType: "Doğalgaz kombi",
      hasElevator: true,
      hasBalcony: true,
      hasParking: true,
      familyFriendly: true,
      suitableForOfficer: true,
      moveOutDate: "2026-06-15",
      landlordContactAvailable: true,
      petAllowed: false,
      nearbyInstitution: "Bakanlık binasına 10 dk",
      houseFeatures: "Eşyalı, ankastre mutfak, balkonlu",
    },
  }),
  baseListing({
    id: mockId(),
    category: "ev-devri",
    title: "İzmir Bornova 3+1 öğretmen evi devri",
    description: "MEB tayini aldım. Okula yürüme mesafesinde, ferah daire.",
    contactName: "Mehmet T.",
    whatsapp: "05559876543",
    cityFrom: "İzmir",
    districtFrom: "Bornova",
    images: mockImages("ev-izmir", 2),
    status: "approved",
    isUrgent: false,
    isFeatured: false,
    reportCount: 0,
    details: {
      neighborhood: "Erzene",
      roomCount: "3+1",
      floor: 2,
      rentPrice: 22000,
      deposit: 22000,
      furnished: "kısmen",
      hasElevator: false,
      hasBalcony: true,
      hasParking: false,
      familyFriendly: true,
      suitableForOfficer: true,
      landlordContactAvailable: true,
      petAllowed: true,
      heatingType: "Merkezi",
    },
  }),
  baseListing({
    id: mockId(),
    category: "ev-devri",
    title: "Antalya Muratpaşa 1+1 hızlı devir",
    description: "Yaz sezonu öncesi devretmek istiyorum. Denize yakın.",
    contactName: "Zeynep A.",
    whatsapp: "05441112233",
    cityFrom: "Antalya",
    districtFrom: "Muratpaşa",
    images: mockImages("ev-antalya", 4),
    status: "approved",
    isUrgent: false,
    isFeatured: false,
    reportCount: 0,
    details: {
      neighborhood: "Şirinyalı",
      roomCount: "1+1",
      rentPrice: 14000,
      furnished: "evet",
      hasElevator: true,
      hasBalcony: false,
      hasParking: true,
      familyFriendly: false,
      suitableForOfficer: true,
      landlordContactAvailable: false,
      petAllowed: false,
    },
  }),
  baseListing({
    id: mockId(),
    category: "ev-devri",
    title: "Erzurum Yakutiye 2+1 memur lojmanına yakın",
    description: "Kışa hazır, doğalgazlı, aidat düşük.",
    contactName: "Can Y.",
    whatsapp: "05334445566",
    cityFrom: "Erzurum",
    districtFrom: "Yakutiye",
    images: mockImages("ev-erzurum", 2),
    status: "approved",
    isUrgent: false,
    isFeatured: false,
    reportCount: 0,
    details: {
      neighborhood: "Yenişehir",
      roomCount: "2+1",
      rentPrice: 9500,
      furnished: "hayır",
      hasElevator: false,
      hasBalcony: true,
      hasParking: true,
      familyFriendly: true,
      suitableForOfficer: true,
      landlordContactAvailable: true,
      petAllowed: true,
    },
  }),
  baseListing({
    id: mockId(),
    category: "ev-devri",
    title: "Trabzon Ortahisar 4+1 aile evi devri",
    description: "Geniş aile için uygun, 2 banyolu, manzaralı.",
    contactName: "Selin M.",
    whatsapp: "05367778899",
    cityFrom: "Trabzon",
    districtFrom: "Ortahisar",
    images: mockImages("ev-trabzon", 3),
    status: "pending",
    isUrgent: false,
    isFeatured: false,
    reportCount: 0,
    details: {
      neighborhood: "Boztepe altı",
      roomCount: "4+1",
      rentPrice: 16000,
      furnished: "evet",
      hasElevator: false,
      hasBalcony: true,
      hasParking: true,
      familyFriendly: true,
      suitableForOfficer: true,
      landlordContactAvailable: true,
      petAllowed: false,
    },
  }),

  // —— Eşya Devri / Satış (5) ——
  baseListing({
    id: mockId(),
    category: "esya-devri",
    title: "Erzurum Arçelik beyaz eşya — satılık buzdolabı + çamaşır",
    description:
      "Tayin nedeniyle satılıyor. Buzdolabı No-Frost, çamaşır makinesi 8 kg. Yerinde görülebilir.",
    contactName: "Can Y.",
    whatsapp: "05334445566",
    cityFrom: "Erzurum",
    districtFrom: "Yakutiye",
    price: 11500,
    images: mockImages("esya-satilik-beyaz", 3),
    status: "approved",
    isUrgent: true,
    isFeatured: false,
    reportCount: 0,
    details: {
      itemCategory: "beyaz-esya",
      condition: "kullanilmis",
      listingIntent: "satilik",
      askingPrice: 11500,
      originalPrice: 22000,
      negotiable: true,
      urgentSale: true,
      paymentPreference: "nakit",
      reasonForSale: "tayin",
      brand: "Arçelik",
      pickupAddressNote: "Yakutiye merkez, akşam 18:00 sonrası",
      itemSetIncluded: "Buzdolabı + çamaşır makinesi",
      quantity: 2,
      pickupOnly: true,
      deliveryIncluded: false,
      bulkSale: true,
      warrantyAvailable: false,
    },
  }),
  baseListing({
    id: mockId(),
    category: "esya-devri",
    title: "Ankara Keçiören — ücretsiz çocuk odası eşyası",
    description:
      "Bebek büyüdü, ihtiyaç sahibi aileye ücretsiz verilecek. Beşik, dolap, mama sandalyesi.",
    contactName: "Elif D.",
    whatsapp: "05329998877",
    cityFrom: "Ankara",
    districtFrom: "Keçiören",
    price: 0,
    images: mockImages("esya-ucretsiz-cocuk", 2),
    status: "approved",
    isUrgent: false,
    isFeatured: true,
    reportCount: 0,
    details: {
      itemCategory: "cocuk-bebek",
      condition: "kullanilmis",
      listingIntent: "ucretsiz",
      negotiable: false,
      urgentSale: false,
      reasonForSale: "ihtiyac-fazlasi",
      itemSetIncluded: "Beşik, gardırop, mama sandalyesi, alt değiştirme",
      pickupAddressNote: "Site güvenliği önceden aranmalı",
      quantity: 1,
      pickupOnly: true,
      deliveryIncluded: false,
      bulkSale: false,
      warrantyAvailable: false,
    },
  }),
  baseListing({
    id: mockId(),
    category: "esya-devri",
    title: "İstanbul Kadıköy — takas: TV karşılığı bisiklet veya tablet",
    description:
      "43 inç Smart TV, az kullanılmış. Takas: çocuk bisikleti (20 jant) veya iPad benzeri tablet ile değişim düşünüyorum. Ciddi teklifler yazın.",
    contactName: "Burak S.",
    whatsapp: "05335556677",
    cityFrom: "İstanbul",
    districtFrom: "Kadıköy",
    price: 0,
    images: mockImages("esya-takas-tv", 2),
    status: "approved",
    isUrgent: false,
    isFeatured: false,
    reportCount: 0,
    details: {
      itemCategory: "elektronik",
      condition: "az-kullanilmis",
      listingIntent: "takas",
      negotiable: true,
      urgentSale: false,
      paymentPreference: "fark-etmez",
      reasonForSale: "tayin",
      brand: "Samsung",
      itemSetIncluded: "TV + kumanda + duvar aparatı",
      pickupAddressNote: "Moda civarı, hafta sonu uygun",
      quantity: 1,
      pickupOnly: true,
      deliveryIncluded: false,
      bulkSale: false,
      warrantyAvailable: true,
    },
  }),
  baseListing({
    id: mockId(),
    category: "esya-devri",
    title: "Samsun Atakum — komple ev eşyası satılık",
    description:
      "3+1 evin tamamı: salon, yatak odası, mutfak beyaz eşya dahil. Tayin nedeniyle tek seferde devredilecek.",
    contactName: "Hakan Ö.",
    whatsapp: "05401234567",
    cityFrom: "Samsun",
    districtFrom: "Atakum",
    price: 42000,
    images: mockImages("esya-komple-samsun", 4),
    status: "approved",
    isUrgent: false,
    isFeatured: true,
    reportCount: 0,
    details: {
      itemCategory: "komple-ev-esyasi",
      condition: "kullanilmis",
      listingIntent: "komple-ev-esyasi",
      askingPrice: 42000,
      originalPrice: 75000,
      negotiable: true,
      urgentSale: false,
      canReserveUntil: "2026-06-20",
      paymentPreference: "havale",
      reasonForSale: "tayin",
      itemSetIncluded: "Salon, yatak odası, mutfak, beyaz eşya paketi",
      pickupAddressNote: "Asansörlü bina, taşıma alıcıya ait",
      quantity: 1,
      pickupOnly: true,
      deliveryIncluded: false,
      bulkSale: true,
      warrantyAvailable: false,
    },
  }),
  baseListing({
    id: mockId(),
    category: "esya-devri",
    title: "Antalya Muratpaşa — devredilecek salon takımı",
    description:
      "L koltuk ve sehpa seti devredilecek. Depozito devri yok, sadece eşya devri. Yerinde teslim.",
    contactName: "Zeynep A.",
    whatsapp: "05441112233",
    cityFrom: "Antalya",
    districtFrom: "Muratpaşa",
    price: 7500,
    images: mockImages("esya-devir-mobilya", 2),
    status: "approved",
    isUrgent: false,
    isFeatured: false,
    reportCount: 0,
    details: {
      itemCategory: "mobilya",
      condition: "az-kullanilmis",
      listingIntent: "devredilecek",
      askingPrice: 7500,
      originalPrice: 14000,
      negotiable: true,
      urgentSale: false,
      paymentPreference: "elden",
      reasonForSale: "tayin",
      itemSetIncluded: "L koltuk, sehpa, TV ünitesi",
      pickupAddressNote: "Şirinyalı, 2. kat",
      quantity: 1,
      pickupOnly: true,
      deliveryIncluded: false,
      bulkSale: false,
      warrantyAvailable: false,
    },
  }),

  // —— Nakliye Arıyorum (5) ——
  baseListing({
    id: mockId(),
    category: "nakliye-ariyorum",
    title: "Ankara → İzmir 2+1 eşya taşıma",
    description: "Haziran ortası çıkış. Ortak kamyon tercih ederim.",
    contactName: "Burak S.",
    whatsapp: "05335556677",
    cityFrom: "Ankara",
    districtFrom: "Çankaya",
    cityTo: "İzmir",
    districtTo: "Bornova",
    availableDate: "2026-06-12",
    availableTimeStart: "09:00",
    availableTimeEnd: "18:00",
    images: mockImages("nak-ank-izm", 1),
    status: "approved",
    isUrgent: true,
    isFeatured: false,
    reportCount: 0,
    details: {
      loadType: "2+1",
      elevatorNeededAtPickup: true,
      elevatorNeededAtDelivery: false,
      packingNeeded: true,
      insuranceRequested: true,
      flexibleDate: false,
      pickupHasElevator: true,
      deliveryHasElevator: false,
      wantsSharedTruck: true,
      budgetRange: "15.000 – 22.000 TL",
      pickupFloor: 4,
      deliveryFloor: 2,
    },
  }),
  baseListing({
    id: mockId(),
    category: "nakliye-ariyorum",
    title: "İstanbul → Diyarbakır parça eşya",
    description: "4-5 koli + küçük mobilya. Paylaşımlı nakliye arıyorum.",
    contactName: "Ayşe K.",
    whatsapp: "05321234567",
    cityFrom: "İstanbul",
    cityTo: "Diyarbakır",
    availableDate: "2026-06-05",
    images: [],
    status: "approved",
    isUrgent: false,
    isFeatured: false,
    reportCount: 0,
    details: {
      loadType: "parca-esya",
      elevatorNeededAtPickup: false,
      elevatorNeededAtDelivery: false,
      packingNeeded: false,
      insuranceRequested: false,
      flexibleDate: true,
      pickupHasElevator: false,
      deliveryHasElevator: false,
      wantsSharedTruck: true,
      budgetRange: "3.000 – 5.000 TL",
    },
  }),
  baseListing({
    id: mockId(),
    category: "nakliye-ariyorum",
    title: "Trabzon → Ankara komple ev taşıma",
    description: "3+1 komple ev. Sigortalı firma tercih.",
    contactName: "Selin M.",
    whatsapp: "05367778899",
    cityFrom: "Trabzon",
    cityTo: "Ankara",
    availableDate: "2026-07-01",
    images: mockImages("nak-trb-ank", 1),
    status: "approved",
    isUrgent: false,
    isFeatured: true,
    reportCount: 0,
    details: {
      loadType: "komple-ev",
      packingNeeded: true,
      insuranceRequested: true,
      flexibleDate: false,
      elevatorNeededAtPickup: false,
      elevatorNeededAtDelivery: true,
      pickupHasElevator: false,
      deliveryHasElevator: true,
      wantsSharedTruck: false,
      budgetRange: "Teklif alınacak",
    },
  }),
  baseListing({
    id: mockId(),
    category: "nakliye-ariyorum",
    title: "Bursa → Antalya beyaz eşya",
    description: "Buzdolabı ve çamaşır makinesi taşınacak.",
    contactName: "Mehmet T.",
    whatsapp: "05559876543",
    cityFrom: "Bursa",
    cityTo: "Antalya",
    availableDate: "2026-06-20",
    images: [],
    status: "approved",
    isUrgent: false,
    isFeatured: false,
    reportCount: 0,
    details: {
      loadType: "beyaz-esya",
      insuranceRequested: true,
      flexibleDate: true,
      elevatorNeededAtPickup: false,
      elevatorNeededAtDelivery: false,
      packingNeeded: false,
      pickupHasElevator: false,
      deliveryHasElevator: false,
      wantsSharedTruck: true,
      budgetRange: "4.000 – 7.000 TL",
    },
  }),
  baseListing({
    id: mockId(),
    category: "nakliye-ariyorum",
    title: "Bursa → Siirt 2+1 eşya taşıma",
    description:
      "Haziran ortası çıkış. Güneydoğu rotası; sigortalı ve kapasiteli araç tercih ederim.",
    contactName: "Can Y.",
    whatsapp: "05351112233",
    cityFrom: "Bursa",
    districtFrom: "Osmangazi",
    cityTo: "Siirt",
    districtTo: "Merkez",
    availableDate: "2026-06-15",
    availableTimeStart: "08:00",
    availableTimeEnd: "14:00",
    images: mockImages("nak-bur-sii", 2),
    status: "approved",
    isUrgent: true,
    isFeatured: true,
    reportCount: 0,
    details: {
      loadType: "2+1",
      elevatorNeededAtPickup: false,
      elevatorNeededAtDelivery: false,
      packingNeeded: true,
      insuranceRequested: true,
      flexibleDate: true,
      pickupHasElevator: false,
      deliveryHasElevator: false,
      wantsSharedTruck: true,
      budgetRange: "12.000 – 18.000 TL",
      preferredVehicleType: "kamyon",
    },
  }),
  baseListing({
    id: mockId(),
    category: "nakliye-ariyorum",
    title: "Samsun → Erzurum ofis eşyası",
    description: "Masa, dolap, 2 koli evrak.",
    contactName: "Elif D.",
    whatsapp: "05329998877",
    cityFrom: "Samsun",
    cityTo: "Erzurum",
    availableDate: "2026-06-08",
    images: [],
    status: "pending",
    isUrgent: false,
    isFeatured: false,
    reportCount: 0,
    details: {
      loadType: "ofis",
      wantsSharedTruck: true,
      packingNeeded: false,
      insuranceRequested: false,
      flexibleDate: false,
      elevatorNeededAtPickup: false,
      elevatorNeededAtDelivery: false,
      pickupHasElevator: false,
      deliveryHasElevator: false,
      budgetRange: "2.500 – 4.000 TL",
    },
  }),

  // —— Nakliyeci Araç (5) ——
  baseListing({
    id: mockId(),
    category: "nakliyeci-arac-ilani",
    title: "Ankara → İzmir panelvan — %35 boş kapasite",
    description: "Sigortalı taşıma. Asansörlü yükleme mevcut.",
    contactName: "Karadeniz Nakliyat",
    whatsapp: "05321112233",
    cityFrom: "Ankara",
    cityTo: "İzmir",
    price: 4500,
    images: mockImages("arac-ank-izm", 2),
    status: "approved",
    isUrgent: false,
    isFeatured: true,
    reportCount: 0,
    details: {
      companyName: "Karadeniz Nakliyat",
      vehicleType: "panelvan",
      totalCapacityM3: 18,
      usedCapacityPercent: 65,
      availableCapacityPercent: 35,
      canTakeRoomEquivalent: "1+1",
      hasLift: true,
      hasTransportInsurance: true,
      hasPackingService: true,
      hasAssemblyService: false,
      departureDate: "2026-06-14",
      departureTimeStart: "08:00",
      departureTimeEnd: "10:00",
      priceType: "masraf-paylasimi",
      basePrice: 4500,
      verifiedCarrier: true,
    },
  }),
  baseListing({
    id: mockId(),
    category: "nakliyeci-arac-ilani",
    title: "İstanbul → Samsun kamyonet — parça eşya alınır",
    description: "Orta kapasite boş. Ekstra durak: Bursa.",
    contactName: "Marmara Express",
    whatsapp: "05449990011",
    cityFrom: "İstanbul",
    cityTo: "Samsun",
    images: mockImages("arac-ist-sam", 2),
    status: "approved",
    isUrgent: false,
    isFeatured: false,
    reportCount: 0,
    details: {
      companyName: "Marmara Express",
      vehicleType: "kamyonet",
      totalCapacityM3: 28,
      usedCapacityPercent: 80,
      availableCapacityPercent: 20,
      canTakeRoomEquivalent: "parca",
      hasLift: false,
      hasTransportInsurance: true,
      hasPackingService: false,
      hasAssemblyService: false,
      routeStops: "Bursa",
      departureDate: "2026-06-10",
      priceType: "teklif-al",
      verifiedCarrier: false,
    },
  }),
  baseListing({
    id: mockId(),
    category: "nakliyeci-arac-ilani",
    title: "Antalya → Ankara kamyon — %50 boş",
    description: "Büyük hacim. 2+1 eşya alınabilir.",
    contactName: "Akdeniz Lojistik",
    whatsapp: "05326667788",
    cityFrom: "Antalya",
    cityTo: "Ankara",
    images: mockImages("arac-ant-ank", 3),
    status: "approved",
    isUrgent: true,
    isFeatured: false,
    reportCount: 0,
    details: {
      vehicleType: "kamyon",
      totalCapacityM3: 45,
      usedCapacityPercent: 50,
      availableCapacityPercent: 50,
      canTakeRoomEquivalent: "2+1",
      hasLift: true,
      hasTransportInsurance: true,
      hasPackingService: true,
      hasAssemblyService: true,
      departureDate: "2026-06-18",
      departureTimeStart: "06:00",
      priceType: "sabit-fiyat",
      basePrice: 12000,
      verifiedCarrier: true,
    },
  }),
  baseListing({
    id: mockId(),
    category: "nakliyeci-arac-ilani",
    title: "Erzurum → Trabzon tır — sınırlı kapasite",
    description: "Uzun rota, sigortalı, profesyonel ekip.",
    contactName: "Doğu Ekspres",
    whatsapp: "05328889900",
    cityFrom: "Erzurum",
    cityTo: "Trabzon",
    images: mockImages("arac-erz-trb", 1),
    status: "approved",
    isUrgent: false,
    isFeatured: false,
    reportCount: 0,
    details: {
      vehicleType: "tir",
      totalCapacityM3: 80,
      usedCapacityPercent: 88,
      availableCapacityPercent: 12,
      canTakeRoomEquivalent: "parca",
      hasLift: false,
      hasTransportInsurance: true,
      hasPackingService: false,
      hasAssemblyService: false,
      departureDate: "2026-06-22",
      priceType: "teklif-al",
      verifiedCarrier: true,
    },
  }),
  baseListing({
    id: mockId(),
    category: "nakliyeci-arac-ilani",
    title: "Bursa → İzmir panelvan — %60 boş kapasite",
    description: "Hızlı teslimat. Paketleme hizmeti opsiyonel.",
    contactName: "Ege Hızlı Taşıma",
    whatsapp: "05324443322",
    cityFrom: "Bursa",
    cityTo: "İzmir",
    images: mockImages("arac-bur-izm", 2),
    status: "approved",
    isUrgent: false,
    isFeatured: false,
    reportCount: 0,
    details: {
      vehicleType: "panelvan",
      totalCapacityM3: 16,
      usedCapacityPercent: 40,
      availableCapacityPercent: 60,
      canTakeRoomEquivalent: "1+1",
      hasLift: true,
      hasTransportInsurance: false,
      hasPackingService: true,
      hasAssemblyService: false,
      departureDate: "2026-06-11",
      priceType: "masraf-paylasimi",
      basePrice: 3200,
      verifiedCarrier: false,
    },
  }),
  baseListing({
    id: mockId(),
    category: "nakliyeci-arac-ilani",
    title: "Bursa → Siirt kamyon — %45 boş, 3+1 alınır",
    description: "Doğrudan güneydoğu hattı. Sigortalı, 2+1 ve üzeri eşya için uygun.",
    contactName: "Güneydoğu Hat Nakliyat",
    whatsapp: "05359991122",
    cityFrom: "Bursa",
    cityTo: "Siirt",
    price: 14000,
    images: mockImages("arac-bur-sii", 2),
    status: "approved",
    isUrgent: false,
    isFeatured: true,
    reportCount: 0,
    details: {
      companyName: "Güneydoğu Hat Nakliyat",
      vehicleType: "kamyon",
      totalCapacityM3: 42,
      usedCapacityPercent: 55,
      availableCapacityPercent: 45,
      canTakeRoomEquivalent: "3+1",
      hasLift: true,
      hasTransportInsurance: true,
      hasPackingService: true,
      hasAssemblyService: false,
      departureDate: "2026-06-15",
      departureTimeStart: "07:00",
      departureTimeEnd: "09:00",
      priceType: "teklif-al",
      verifiedCarrier: true,
    },
  }),
  baseListing({
    id: mockId(),
    category: "nakliyeci-arac-ilani",
    title: "Bursa → Diyarbakır kamyonet — yakın güzergâh",
    description: "Siirt hattına yakın varış. 2+1 eşya alınabilir.",
    contactName: "Marmara Güney Hat",
    whatsapp: "05448887766",
    cityFrom: "Bursa",
    cityTo: "Diyarbakır",
    images: mockImages("arac-bur-diy", 1),
    status: "approved",
    isUrgent: false,
    isFeatured: false,
    reportCount: 0,
    details: {
      vehicleType: "kamyonet",
      totalCapacityM3: 26,
      usedCapacityPercent: 35,
      availableCapacityPercent: 65,
      canTakeRoomEquivalent: "2+1",
      hasLift: false,
      hasTransportInsurance: true,
      hasPackingService: false,
      hasAssemblyService: false,
      departureDate: "2026-06-14",
      departureTimeStart: "08:30",
      priceType: "masraf-paylasimi",
      basePrice: 8500,
      verifiedCarrier: true,
    },
  }),
  baseListing({
    id: mockId(),
    category: "nakliyeci-arac-ilani",
    title: "Bursa → Mardin panelvan — sınırlı kapasite",
    description: "Güneydoğu alternatif rota. Parça ve küçük eşya.",
    contactName: "Sınır Ekspres",
    whatsapp: "05323334455",
    cityFrom: "Bursa",
    cityTo: "Mardin",
    images: [],
    status: "approved",
    isUrgent: false,
    isFeatured: false,
    reportCount: 0,
    details: {
      vehicleType: "panelvan",
      totalCapacityM3: 14,
      usedCapacityPercent: 75,
      availableCapacityPercent: 25,
      canTakeRoomEquivalent: "1+1",
      hasLift: false,
      hasTransportInsurance: false,
      hasPackingService: false,
      hasAssemblyService: false,
      departureDate: "2026-06-16",
      priceType: "teklif-al",
      verifiedCarrier: false,
    },
  }),
  baseListing({
    id: mockId(),
    category: "nakliyeci-arac-ilani",
    title: "Ankara → Siirt kamyon — alternatif çıkış",
    description: "İç Anadolu çıkışlı Siirt hattı. Büyük hacim.",
    contactName: "Anadolu Güney Lojistik",
    whatsapp: "05326665544",
    cityFrom: "Ankara",
    cityTo: "Siirt",
    images: mockImages("arac-ank-sii", 2),
    status: "approved",
    isUrgent: false,
    isFeatured: false,
    reportCount: 0,
    details: {
      vehicleType: "kamyon",
      totalCapacityM3: 48,
      usedCapacityPercent: 40,
      availableCapacityPercent: 60,
      canTakeRoomEquivalent: "3+1",
      hasLift: true,
      hasTransportInsurance: true,
      hasPackingService: true,
      hasAssemblyService: true,
      departureDate: "2026-06-17",
      priceType: "sabit-fiyat",
      basePrice: 16000,
      verifiedCarrier: true,
    },
  }),
  baseListing({
    id: mockId(),
    category: "nakliyeci-arac-ilani",
    title: "Konya → Diyarbakır tır — düşük boş kapasite",
    description: "Güzergâh kesişimi olabilir; sınırlı yer (~1+1).",
    contactName: "Orta Anadolu Hat",
    whatsapp: "05327778811",
    cityFrom: "Konya",
    cityTo: "Diyarbakır",
    images: [],
    status: "approved",
    isUrgent: false,
    isFeatured: false,
    reportCount: 0,
    details: {
      vehicleType: "tir",
      totalCapacityM3: 72,
      usedCapacityPercent: 92,
      availableCapacityPercent: 8,
      canTakeRoomEquivalent: "1+1",
      hasLift: false,
      hasTransportInsurance: true,
      hasPackingService: false,
      hasAssemblyService: false,
      departureDate: "2026-06-15",
      priceType: "teklif-al",
      verifiedCarrier: false,
    },
  }),

  // —— Şehir Sorusu (5) ——
  baseListing({
    id: mockId(),
    category: "sehir-sorusu",
    title: "Trabzon'da öğretmen için mahalle önerisi",
    description: "İlk tayin. Okula yakın ve güvenli mahalle arıyorum.",
    contactName: "Selin M.",
    whatsapp: "05367778899",
    cityFrom: "Trabzon",
    images: [],
    status: "approved",
    isUrgent: false,
    isFeatured: false,
    reportCount: 0,
    details: {
      targetCity: "Trabzon",
      targetDistrict: "Ortahisar",
      questionType: "mahalle",
      officerGroup: "ogretmen",
      answerStatus: "cevap-bekliyor",
    },
  }),
  baseListing({
    id: mockId(),
    category: "sehir-sorusu",
    title: "Şanlıurfa kira seviyesi — polis tayini",
    description: "Ailemle geleceğim, 2+1 kira ne kadar?",
    contactName: "Hakan Ö.",
    whatsapp: "05401234567",
    cityFrom: "Şanlıurfa",
    images: [],
    status: "approved",
    isUrgent: false,
    isFeatured: false,
    reportCount: 0,
    details: {
      targetCity: "Şanlıurfa",
      questionType: "kira",
      officerGroup: "polis",
      answerStatus: "cevaplandi",
    },
  }),
  baseListing({
    id: mockId(),
    category: "sehir-sorusu",
    title: "Erzurum lojman ve kurum çevresi",
    description: "Sağlıkçı tayini. Hastaneye yakın konaklama?",
    contactName: "Can Y.",
    whatsapp: "05334445566",
    cityFrom: "Erzurum",
    images: [],
    status: "approved",
    isUrgent: true,
    isFeatured: false,
    reportCount: 0,
    details: {
      targetCity: "Erzurum",
      targetDistrict: "Yakutiye",
      questionType: "lojman",
      officerGroup: "saglikci",
      answerStatus: "cevap-bekliyor",
    },
  }),
  baseListing({
    id: mockId(),
    category: "sehir-sorusu",
    title: "Ankara ulaşım — Çankaya'dan Etimesgut'a",
    description: "Günlük işe gidiş nasıl daha kolay olur?",
    contactName: "Ayşe K.",
    whatsapp: "05321234567",
    cityFrom: "Ankara",
    images: [],
    status: "approved",
    isUrgent: false,
    isFeatured: false,
    reportCount: 0,
    details: {
      targetCity: "Ankara",
      targetDistrict: "Etimesgut",
      questionType: "ulasim",
      officerGroup: "diger",
      answerStatus: "cevap-bekliyor",
    },
  }),
  baseListing({
    id: mockId(),
    category: "sehir-sorusu",
    title: "Antalya okul çevresi — imam hatip tayini",
    description: "Çocuklu aile için okul ve mahalle tavsiyesi.",
    contactName: "Mehmet T.",
    whatsapp: "05559876543",
    cityFrom: "Antalya",
    images: [],
    status: "pending",
    isUrgent: false,
    isFeatured: false,
    reportCount: 0,
    details: {
      targetCity: "Antalya",
      targetDistrict: "Kepez",
      questionType: "okul",
      officerGroup: "imam",
      answerStatus: "cevap-bekliyor",
    },
  }),
  ...MOCK_HIZMET_VERENLER_LISTINGS,
];
