import { daysAgo } from "./helpers";
import type { Review } from "@/types/user-profile";

export const MOCK_REVIEWS: Review[] = [
  {
    id: "rev-1",
    fromUserId: "usr-burak",
    toUserId: "usr-karadeniz",
    rating: 5,
    comment: "Ankara–İzmir taşımamız sorunsuz tamamlandı. Zamanında ve özenli.",
    reviewTags: ["zamaninda-geldi", "guvenilir", "profesyonel", "tavsiye-ederim"],
    createdAt: daysAgo(14),
    isVerifiedTransaction: true,
  },
  {
    id: "rev-2",
    fromUserId: "usr-ayse",
    toUserId: "usr-marmara",
    rating: 4,
    comment: "İletişim iyiydi, fiyat makul. Küçük gecikme oldu ama bilgilendirdiler.",
    reviewTags: ["iletisim-iyi", "fiyat-adil"],
    createdAt: daysAgo(30),
    isVerifiedTransaction: true,
  },
  {
    id: "rev-3",
    fromUserId: "usr-mehmet",
    toUserId: "usr-ayse",
    rating: 5,
    comment: "Ev devri sürecinde çok yardımcı oldu, evraklar eksiksizdi.",
    reviewTags: ["guvenilir", "iletisim-iyi", "tavsiye-ederim"],
    createdAt: daysAgo(45),
    isVerifiedTransaction: true,
  },
  {
    id: "rev-4",
    fromUserId: "usr-selin",
    toUserId: "usr-zeynep",
    rating: 5,
    comment: "Emlak danışmanlığı net ve şeffaftı.",
    reviewTags: ["profesyonel", "fiyat-adil", "tavsiye-ederim"],
    createdAt: daysAgo(20),
    isVerifiedTransaction: false,
  },
  {
    id: "rev-5",
    fromUserId: "usr-can",
    toUserId: "usr-karadeniz",
    rating: 5,
    comment: "Bursa–Siirt hattında sigortalı taşıma, eşyalar hasarsız geldi.",
    reviewTags: ["zamaninda-geldi", "esya-durum-dogru", "guvenilir"],
    createdAt: daysAgo(7),
    isVerifiedTransaction: true,
  },
  {
    id: "rev-6",
    fromUserId: "usr-elif",
    toUserId: "usr-marmara",
    rating: 4,
    comment: "Parça eşya taşıması uygun fiyatlıydı.",
    reviewTags: ["fiyat-adil", "temiz-teslim"],
    createdAt: daysAgo(60),
    isVerifiedTransaction: true,
  },
  {
    id: "rev-7",
    fromUserId: "usr-hakan",
    toUserId: "usr-mehmet",
    rating: 4,
    comment: "Kiracı devri düzgün ilerledi.",
    reviewTags: ["guvenilir", "iletisim-iyi"],
    createdAt: daysAgo(90),
    isVerifiedTransaction: true,
  },
  {
    id: "rev-8",
    fromUserId: "usr-burak",
    toUserId: "usr-ayse",
    rating: 5,
    comment: "Eşya ilanında tarif ettiği gibi ürünlerdi.",
    reviewTags: ["esya-durum-dogru", "tavsiye-ederim"],
    createdAt: daysAgo(10),
    isVerifiedTransaction: false,
  },
  {
    id: "rev-9",
    fromUserId: "usr-karadeniz",
    toUserId: "usr-burak",
    rating: 5,
    comment: "Yük hazırlığı zamanında, iletişim net.",
    reviewTags: ["iletisim-iyi", "zamaninda-geldi"],
    createdAt: daysAgo(12),
    isVerifiedTransaction: true,
  },
  {
    id: "rev-10",
    fromUserId: "usr-ayse",
    toUserId: "usr-karadeniz",
    rating: 5,
    comment: "Onaylı nakliyeci rozeti hak ediyor, profesyonel ekip.",
    reviewTags: ["profesyonel", "guvenilir", "tavsiye-ederim"],
    createdAt: daysAgo(5),
    isVerifiedTransaction: true,
  },
  {
    id: "rev-11",
    fromUserId: "usr-mehmet",
    toUserId: "usr-marmara",
    rating: 3,
    comment: "Taşıma tamamlandı ancak randevu saati kaydı.",
    reviewTags: ["iletisim-iyi"],
    createdAt: daysAgo(40),
    isVerifiedTransaction: true,
  },
  {
    id: "rev-13",
    fromUserId: "usr-can",
    toUserId: "usr-marmara",
    rating: 4,
    comment: "Diyarbakır yakın hat alternatifi işime yaradı.",
    reviewTags: ["profesyonel", "fiyat-adil"],
    createdAt: daysAgo(8),
    isVerifiedTransaction: true,
  },
  {
    id: "rev-14",
    fromUserId: "usr-zeynep",
    toUserId: "usr-hakan",
    rating: 4,
    comment: "Ev sahibi olarak süreç şeffaftı.",
    reviewTags: ["guvenilir"],
    createdAt: daysAgo(55),
    isVerifiedTransaction: true,
  },
  {
    id: "rev-15",
    fromUserId: "usr-elif",
    toUserId: "usr-ayse",
    rating: 5,
    comment: "Hızlı dönüş, güvenilir satıcı.",
    reviewTags: ["iletisim-iyi", "guvenilir", "tavsiye-ederim"],
    createdAt: daysAgo(2),
    isVerifiedTransaction: false,
  },
  {
    id: "rev-16",
    fromUserId: "usr-marmara",
    toUserId: "usr-can",
    rating: 5,
    comment: "Yük listesi net hazırlanmıştı, teslim kolaydı.",
    reviewTags: ["zamaninda-geldi", "iletisim-iyi"],
    createdAt: daysAgo(6),
    isVerifiedTransaction: true,
  },
];
