import { daysAgo } from "./helpers";
import type { TransactionHistory } from "@/types/user-profile";

export const MOCK_TRANSACTIONS: TransactionHistory[] = [
  {
    id: "txn-1",
    listingTitle: "Ankara → İzmir 2+1 eşya taşıma",
    listingCategory: "nakliye-ariyorum",
    fromUserId: "usr-burak",
    toUserId: "usr-karadeniz",
    transactionType: "nakliye",
    status: "tamamlandi",
    completedAt: daysAgo(14),
    ratingGiven: 5,
    reviewId: "rev-1",
  },
  {
    id: "txn-2",
    listingTitle: "Ankara Çankaya 2+1 ev devri",
    listingCategory: "ev-devri",
    fromUserId: "usr-ayse",
    toUserId: "usr-mehmet",
    transactionType: "ev-devri",
    status: "tamamlandi",
    completedAt: daysAgo(45),
    ratingGiven: 5,
    reviewId: "rev-3",
  },
  {
    id: "txn-3",
    listingTitle: "Bursa → Siirt 2+1 eşya taşıma",
    listingCategory: "nakliye-ariyorum",
    fromUserId: "usr-can",
    toUserId: "usr-karadeniz",
    transactionType: "nakliye",
    status: "tamamlandi",
    completedAt: daysAgo(7),
    ratingGiven: 5,
    reviewId: "rev-5",
  },
  {
    id: "txn-4",
    listingTitle: "İstanbul → Samsun kamyonet",
    listingCategory: "nakliyeci-arac-ilani",
    fromUserId: "usr-elif",
    toUserId: "usr-marmara",
    transactionType: "nakliye",
    status: "tamamlandi",
    completedAt: daysAgo(60),
    ratingGiven: 4,
    reviewId: "rev-6",
  },
  {
    id: "txn-5",
    listingTitle: "Ankara → İzmir panelvan",
    listingCategory: "nakliyeci-arac-ilani",
    fromUserId: "usr-burak",
    toUserId: "usr-karadeniz",
    transactionType: "nakliye",
    status: "devam-ediyor",
  },
  {
    id: "txn-6",
    listingTitle: "İzmir Bornova 3+1 ev devri",
    listingCategory: "ev-devri",
    fromUserId: "usr-mehmet",
    toUserId: "usr-zeynep",
    transactionType: "ev-devri",
    status: "tamamlandi",
    completedAt: daysAgo(30),
    ratingGiven: 4,
  },
  {
    id: "txn-7",
    listingTitle: "Ücretsiz çocuk odası seti",
    listingCategory: "esya-devri",
    fromUserId: "usr-ayse",
    toUserId: "usr-elif",
    transactionType: "esya-satis",
    status: "tamamlandi",
    completedAt: daysAgo(10),
    ratingGiven: 5,
    reviewId: "rev-15",
  },
  {
    id: "txn-9",
    listingTitle: "Bursa → Diyarbakır kamyonet",
    listingCategory: "nakliyeci-arac-ilani",
    fromUserId: "usr-can",
    toUserId: "usr-marmara",
    transactionType: "nakliye",
    status: "tamamlandi",
    completedAt: daysAgo(8),
    ratingGiven: 4,
    reviewId: "rev-13",
  },
  {
    id: "txn-10",
    listingTitle: "Antalya → Ankara kamyon",
    listingCategory: "nakliyeci-arac-ilani",
    fromUserId: "usr-mehmet",
    toUserId: "usr-marmara",
    transactionType: "nakliye",
    status: "sorunlu",
    completedAt: daysAgo(40),
    ratingGiven: 3,
    reviewId: "rev-11",
  },
  {
    id: "txn-11",
    listingTitle: "Bursa depozito devri",
    listingCategory: "ev-devri",
    fromUserId: "usr-hakan",
    toUserId: "usr-mehmet",
    transactionType: "ev-devri",
    status: "tamamlandi",
    completedAt: daysAgo(90),
    ratingGiven: 4,
    reviewId: "rev-7",
  },
  {
    id: "txn-12",
    listingTitle: "Ankara → İzmir 2+1 eşya",
    listingCategory: "nakliye-ariyorum",
    fromUserId: "usr-ayse",
    toUserId: "usr-karadeniz",
    transactionType: "nakliye",
    status: "tamamlandi",
    completedAt: daysAgo(5),
    ratingGiven: 5,
    reviewId: "rev-10",
  },
  {
    id: "txn-13",
    listingTitle: "İstanbul Kadıköy danışmanlık",
    listingCategory: "ev-devri",
    fromUserId: "usr-zeynep",
    toUserId: "usr-selin",
    transactionType: "ev-devri",
    status: "tamamlandi",
    completedAt: daysAgo(20),
    ratingGiven: 5,
    reviewId: "rev-4",
  },
  {
    id: "txn-14",
    listingTitle: "Bursa → Mardin panelvan",
    listingCategory: "nakliyeci-arac-ilani",
    fromUserId: "usr-can",
    toUserId: "usr-marmara",
    transactionType: "nakliye",
    status: "devam-ediyor",
  },
  {
    id: "txn-15",
    listingTitle: "Samsun → Erzurum ofis eşyası",
    listingCategory: "nakliye-ariyorum",
    fromUserId: "usr-elif",
    toUserId: "usr-marmara",
    transactionType: "nakliye",
    status: "iptal",
  },
];
