import { daysAgo } from "./helpers";
import type { CarrierProfile, UserProfile } from "@/types/user-profile";

function avatar(seed: string): string {
  return `https://i.pravatar.cc/150?u=tayin-${seed}`;
}

const MOCK_CORE_USERS: UserProfile[] = [
  {
    id: "usr-ayse",
    fullName: "Ayşe Kaya",
    displayName: "Ayşe K.",
    avatarUrl: avatar("ayse"),
    userType: "memur",
    officerGroup: "ogretmen",
    city: "Ankara",
    district: "Çankaya",
    phone: "05321234567",
    whatsapp: "05321234567",
    email: "ayse.kaya@example.com",
    bio: "MEB tayini sürecinde ev ve eşya ilanları paylaşıyorum. Güvenilir iletişim önceliğim.",
    joinedAt: daysAgo(420),
    lastActiveAt: daysAgo(1),
    isVerified: true,
    isPhoneVerified: true,
    isEmailVerified: true,
    isIdentityVerified: true,
    isCarrierVerified: false,
    trustScore: 92,
    ratingAverage: 4.8,
    ratingCount: 12,
    completedTransactionCount: 9,
    activeListingCount: 3,
    reportCount: 0,
    responseRate: 96,
    averageResponseTime: "2 saat",
    badges: [
      "telefon-dogrulandi",
      "eposta-dogrulandi",
      "guvenilir-kullanici",
      "hizli-donus",
    ],
  },
  {
    id: "usr-mehmet",
    fullName: "Mehmet Tunç",
    displayName: "Mehmet T.",
    avatarUrl: avatar("mehmet"),
    userType: "memur",
    officerGroup: "ogretmen",
    city: "İzmir",
    district: "Bornova",
    phone: "05559876543",
    whatsapp: "05559876543",
    email: "mehmet.tunc@example.com",
    bio: "Öğretmen — ev devri ve nakliye ihtiyaçları için aktif ilan veriyorum.",
    joinedAt: daysAgo(380),
    lastActiveAt: daysAgo(2),
    isVerified: true,
    isPhoneVerified: true,
    isEmailVerified: false,
    isIdentityVerified: false,
    isCarrierVerified: false,
    trustScore: 86,
    ratingAverage: 4.6,
    ratingCount: 8,
    completedTransactionCount: 6,
    activeListingCount: 2,
    reportCount: 0,
    responseRate: 88,
    averageResponseTime: "4 saat",
    badges: ["telefon-dogrulandi", "guvenilir-kullanici"],
  },
  {
    id: "usr-selin",
    fullName: "Selin Mutlu",
    displayName: "Selin M.",
    avatarUrl: avatar("selin"),
    userType: "memur",
    officerGroup: "saglikci",
    city: "Trabzon",
    phone: "05367778899",
    whatsapp: "05367778899",
    bio: "Sağlık Bakanlığı tayini — şehir ve ev arayışı paylaşımları.",
    joinedAt: daysAgo(200),
    lastActiveAt: daysAgo(0),
    isVerified: true,
    isPhoneVerified: true,
    isEmailVerified: true,
    isIdentityVerified: true,
    isCarrierVerified: false,
    trustScore: 88,
    ratingAverage: 4.7,
    ratingCount: 6,
    completedTransactionCount: 4,
    activeListingCount: 2,
    reportCount: 0,
    responseRate: 91,
    averageResponseTime: "3 saat",
    badges: ["telefon-dogrulandi", "eposta-dogrulandi", "hizli-donus"],
  },
  {
    id: "usr-karadeniz",
    fullName: "Karadeniz Nakliyat",
    displayName: "Karadeniz Nakliyat",
    avatarUrl: avatar("karadeniz"),
    userType: "nakliyeci",
    officerGroup: "none",
    city: "Ankara",
    phone: "05321112233",
    whatsapp: "05321112233",
    email: "info@karadeniz-nakliyat.example",
    bio: "Sigortalı taşımacılık. Ankara–İzmir ve güneydoğu hatlarında düzenli seferler.",
    joinedAt: daysAgo(800),
    lastActiveAt: daysAgo(0),
    isVerified: true,
    isPhoneVerified: true,
    isEmailVerified: true,
    isIdentityVerified: true,
    isCarrierVerified: true,
    trustScore: 95,
    ratingAverage: 4.9,
    ratingCount: 34,
    completedTransactionCount: 128,
    activeListingCount: 4,
    reportCount: 0,
    responseRate: 98,
    averageResponseTime: "45 dk",
    badges: [
      "telefon-dogrulandi",
      "eposta-dogrulandi",
      "onayli-nakliyeci",
      "deneyimli-tasiyici",
      "premium-firma",
      "guvenilir-kullanici",
    ],
  },
  {
    id: "usr-marmara",
    fullName: "Marmara Lojistik",
    displayName: "Marmara Express",
    avatarUrl: avatar("marmara"),
    userType: "nakliyeci",
    officerGroup: "none",
    city: "İstanbul",
    phone: "05449990011",
    whatsapp: "05449990011",
    email: "iletisim@marmara-express.example",
    bio: "Marmara ve iç Anadolu güzergâhlarında kamyonet ve kamyon filosu.",
    joinedAt: daysAgo(650),
    lastActiveAt: daysAgo(1),
    isVerified: true,
    isPhoneVerified: true,
    isEmailVerified: true,
    isIdentityVerified: false,
    isCarrierVerified: true,
    trustScore: 89,
    ratingAverage: 4.5,
    ratingCount: 22,
    completedTransactionCount: 76,
    activeListingCount: 5,
    reportCount: 1,
    responseRate: 85,
    averageResponseTime: "1 saat",
    badges: [
      "telefon-dogrulandi",
      "onayli-nakliyeci",
      "deneyimli-tasiyici",
      "hizli-donus",
    ],
  },
  {
    id: "usr-hakan",
    fullName: "Hakan Öztürk",
    displayName: "Hakan Ö.",
    avatarUrl: avatar("hakan"),
    userType: "ev-sahibi",
    officerGroup: "none",
    city: "Bursa",
    phone: "05401234567",
    whatsapp: "05401234567",
    bio: "Kiracı değişimi ve depozito devri konularında deneyimli ev sahibi.",
    joinedAt: daysAgo(300),
    lastActiveAt: daysAgo(3),
    isVerified: false,
    isPhoneVerified: true,
    isEmailVerified: false,
    isIdentityVerified: false,
    isCarrierVerified: false,
    trustScore: 78,
    ratingAverage: 4.3,
    ratingCount: 4,
    completedTransactionCount: 3,
    activeListingCount: 1,
    reportCount: 0,
    responseRate: 72,
    averageResponseTime: "6 saat",
    badges: ["telefon-dogrulandi"],
  },
  {
    id: "usr-zeynep",
    fullName: "Zeynep Arslan",
    displayName: "Zeynep A.",
    avatarUrl: avatar("zeynep"),
    userType: "emlakci",
    officerGroup: "none",
    city: "İstanbul",
    district: "Kadıköy",
    phone: "05441112233",
    whatsapp: "05441112233",
    email: "zeynep@emlak-ornek.example",
    bio: "Tayin eden memurlar için ev devri ve kiralık danışmanlığı.",
    joinedAt: daysAgo(500),
    lastActiveAt: daysAgo(1),
    isVerified: true,
    isPhoneVerified: true,
    isEmailVerified: true,
    isIdentityVerified: false,
    isCarrierVerified: false,
    trustScore: 84,
    ratingAverage: 4.4,
    ratingCount: 11,
    completedTransactionCount: 15,
    activeListingCount: 2,
    reportCount: 0,
    responseRate: 90,
    averageResponseTime: "2 saat",
    badges: ["telefon-dogrulandi", "eposta-dogrulandi", "guvenilir-kullanici"],
  },
  {
    id: "usr-burak",
    fullName: "Burak Şahin",
    displayName: "Burak S.",
    avatarUrl: avatar("burak"),
    userType: "bireysel",
    officerGroup: "none",
    city: "Ankara",
    phone: "05335556677",
    whatsapp: "05335556677",
    bio: "Nakliye ve eşya ilanları — ortak taşıma tercih ediyorum.",
    joinedAt: daysAgo(90),
    lastActiveAt: daysAgo(0),
    isVerified: false,
    isPhoneVerified: true,
    isEmailVerified: false,
    isIdentityVerified: false,
    isCarrierVerified: false,
    trustScore: 71,
    ratingAverage: 4.2,
    ratingCount: 3,
    completedTransactionCount: 2,
    activeListingCount: 2,
    reportCount: 0,
    responseRate: 80,
    averageResponseTime: "5 saat",
    badges: ["telefon-dogrulandi", "yeni-uye"],
  },
  {
    id: "usr-elif",
    fullName: "Elif Demir",
    displayName: "Elif D.",
    avatarUrl: avatar("elif"),
    userType: "bireysel",
    officerGroup: "none",
    city: "Samsun",
    phone: "05329998877",
    whatsapp: "05329998877",
    bio: "Parça eşya ve ofis taşıma ilanları.",
    joinedAt: daysAgo(120),
    lastActiveAt: daysAgo(2),
    isVerified: false,
    isPhoneVerified: true,
    isEmailVerified: false,
    isIdentityVerified: false,
    isCarrierVerified: false,
    trustScore: 68,
    ratingAverage: 4.0,
    ratingCount: 2,
    completedTransactionCount: 1,
    activeListingCount: 2,
    reportCount: 0,
    responseRate: 75,
    averageResponseTime: "8 saat",
    badges: ["telefon-dogrulandi", "yeni-uye"],
  },
  {
    id: "usr-can",
    fullName: "Can Yılmaz",
    displayName: "Can Y.",
    avatarUrl: avatar("can"),
    userType: "bireysel",
    officerGroup: "polis",
    city: "Bursa",
    phone: "05351112233",
    whatsapp: "05351112233",
    bio: "Emniyet tayini — güneydoğu rotası nakliye ihtiyaçları.",
    joinedAt: daysAgo(60),
    lastActiveAt: daysAgo(0),
    isVerified: true,
    isPhoneVerified: true,
    isEmailVerified: true,
    isIdentityVerified: false,
    isCarrierVerified: false,
    trustScore: 82,
    ratingAverage: 4.6,
    ratingCount: 5,
    completedTransactionCount: 3,
    activeListingCount: 3,
    reportCount: 0,
    responseRate: 92,
    averageResponseTime: "3 saat",
    badges: ["telefon-dogrulandi", "hizli-donus"],
  },
];

export const MOCK_CARRIER_PROFILES: CarrierProfile[] = [
  {
    userId: "usr-karadeniz",
    companyName: "Karadeniz Nakliyat",
    taxOrRegistrationNote: "Vergi levhası ve K belgesi onaylı (mock)",
    serviceCities: ["Ankara", "İzmir", "Bursa", "Siirt", "Diyarbakır", "Antalya"],
    vehicleTypes: ["panelvan", "kamyonet", "kamyon"],
    hasLiftService: true,
    hasPackingService: true,
    hasInsurance: true,
    totalMoves: 140,
    completedMoves: 128,
    cancelledMoves: 4,
    vehicleCount: 6,
    verificationStatus: "verified",
    documentsNote: "Sigorta poliçesi ve araç ruhsatları doğrulandı (mock).",
    workingHours: "Hafta içi 08:00 – 20:00",
    serviceDescription:
      "Memur ve kamu personeline özel sigortalı taşımacılık. Ortak kamyon ve komple ev taşıma.",
  },
  {
    userId: "usr-marmara",
    companyName: "Marmara Lojistik Grubu",
    serviceCities: ["İstanbul", "Bursa", "Samsun", "Ankara", "Diyarbakır", "Mardin", "Konya"],
    vehicleTypes: ["kamyonet", "kamyon", "tir"],
    hasLiftService: false,
    hasPackingService: true,
    hasInsurance: true,
    totalMoves: 95,
    completedMoves: 76,
    cancelledMoves: 8,
    vehicleCount: 4,
    verificationStatus: "verified",
    workingHours: "7/24 randevu",
    serviceDescription:
      "Marmara çıkışlı ulusal hatlar. Parça eşyadan tır yüküne kadar esnek kapasite.",
  },
];

function serviceUser(
  id: string,
  fullName: string,
  city: string,
  phone: string,
  trust: number,
  rating: number,
  completed: number,
  badges: UserProfile["badges"],
): UserProfile {
  return {
    id,
    fullName,
    displayName: fullName.split(" ")[0] + " " + (fullName.split(" ")[1]?.[0] ?? "") + ".",
    avatarUrl: avatar(id),
    userType: "hizmet-veren",
    officerGroup: "none",
    city,
    phone,
    whatsapp: phone,
    bio: `${city} bölgesinde tayin sonrası hizmet — güvenilir ve hızlı iletişim.`,
    joinedAt: daysAgo(200),
    lastActiveAt: daysAgo(1),
    isVerified: true,
    isPhoneVerified: true,
    isEmailVerified: false,
    isIdentityVerified: false,
    isCarrierVerified: false,
    trustScore: trust,
    ratingAverage: rating,
    ratingCount: Math.max(3, Math.floor(completed / 2)),
    completedTransactionCount: completed,
    activeListingCount: 1,
    reportCount: 0,
    responseRate: 94,
    averageResponseTime: "2 saat",
    badges,
  };
}

export const MOCK_HIZMET_USERS: UserProfile[] = [
  serviceUser("usr-hizmet-ankara", "Gül Yılmaz", "Ankara", "05321110001", 91, 4.9, 48, [
    "onayli-hizmet-veren",
    "hizli-servis",
    "telefon-dogrulandi",
  ]),
  serviceUser("usr-hizmet-bursa", "Mehmet Usta", "Bursa", "05322220002", 88, 4.7, 62, [
    "deneyimli-usta",
    "guvenilir-kullanici",
  ]),
  serviceUser("usr-hizmet-siirt", "Ahmet Kaya", "Siirt", "05343330003", 85, 4.6, 35, [
    "hizli-servis",
    "telefon-dogrulandi",
  ]),
  serviceUser("usr-hizmet-van", "Van Elektrik", "Van", "05324440004", 90, 4.8, 41, [
    "onayli-hizmet-veren",
    "deneyimli-usta",
  ]),
  serviceUser("usr-hizmet-diyarbakir", "DK Montaj", "Diyarbakır", "05325550005", 87, 4.7, 29, [
    "onayli-hizmet-veren",
  ]),
  serviceUser("usr-hizmet-mardin", "Perde Evi", "Mardin", "05326660006", 84, 4.5, 22, [
    "guvenilir-kullanici",
  ]),
  serviceUser("usr-hizmet-izmir", "Ege Klima", "İzmir", "05327770007", 93, 4.9, 55, [
    "onayli-hizmet-veren",
    "hizli-servis",
    "premium-firma",
  ]),
  serviceUser("usr-hizmet-erzurum", "Doğu Net", "Erzurum", "05328880008", 86, 4.6, 18, [
    "telefon-dogrulandi",
  ]),
  serviceUser("usr-hizmet-istanbul", "Tamirat Pro", "İstanbul", "05329990009", 94, 4.9, 72, [
    "onayli-hizmet-veren",
    "deneyimli-usta",
    "premium-firma",
  ]),
  serviceUser("usr-hizmet-konya", "Selin Arslan", "Konya", "05321010010", 82, 4.5, 15, [
    "hizli-servis",
  ]),
  serviceUser("usr-hizmet-antalya", "Akdeniz Çilingir", "Antalya", "05322110011", 89, 4.8, 88, [
    "onayli-hizmet-veren",
    "hizli-servis",
  ]),
  serviceUser("usr-hizmet-kayseri", "Yük Ekibi", "Kayseri", "05323220012", 80, 4.4, 26, [
    "guvenilir-kullanici",
  ]),
];

/** WhatsApp numarasına göre ilan sahibi kullanıcı eşlemesi */
export const WHATSAPP_TO_USER_ID: Record<string, string> = {
  "05321234567": "usr-ayse",
  "05559876543": "usr-mehmet",
  "05367778899": "usr-selin",
  "05321112233": "usr-karadeniz",
  "05449990011": "usr-marmara",
  "05326667788": "usr-marmara",
  "05328889900": "usr-karadeniz",
  "05324443322": "usr-marmara",
  "05359991122": "usr-karadeniz",
  "05448887766": "usr-marmara",
  "05323334455": "usr-marmara",
  "05326665544": "usr-marmara",
  "05327778811": "usr-marmara",
  "05401234567": "usr-hakan",
  "05441112233": "usr-zeynep",
  "05335556677": "usr-burak",
  "05329998877": "usr-elif",
  "05351112233": "usr-can",
  "05334445566": "usr-can",
  "05321110001": "usr-hizmet-ankara",
  "05322220002": "usr-hizmet-bursa",
  "05343330003": "usr-hizmet-siirt",
  "05324440004": "usr-hizmet-van",
  "05325550005": "usr-hizmet-diyarbakir",
  "05326660006": "usr-hizmet-mardin",
  "05327770007": "usr-hizmet-izmir",
  "05328880008": "usr-hizmet-erzurum",
  "05329990009": "usr-hizmet-istanbul",
  "05321010010": "usr-hizmet-konya",
  "05322110011": "usr-hizmet-antalya",
  "05323220012": "usr-hizmet-kayseri",
};

export const MOCK_USERS: UserProfile[] = [...MOCK_CORE_USERS, ...MOCK_HIZMET_USERS];

export const DEFAULT_MOCK_USER_ID = "usr-ayse";
